import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css"; // Importing  Local-CSS or Component-Level-CSS
import Link from "next/link";
import Blog from "./components/Blog";
export default function Home() {
  return (
    <div className={styles.container}>
      {/* NExt JS Provides A-Built-In Head To Directly Edit The meta, title... tags
      for optimization, & remember we could do the same thing with JS, Just Like
      We Did In -> "React" */}
      <Head>
        <title>hey there</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Generated, by, create, next, app" />
        <link rel="icon" href="/favicon.ico" />
        {/* We don't need to jump folders to reach in the public, instead we'll directly Access The [External-JS-File] From THe Public-Folder  */}
        <script src="./demo.js"></script>{" "}
        {/*We Won't Use this instead, we'll use lazy-loading with Next-JS deffault Component*/}
        {/* <Script src="./demo.js"></Script> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mr. Blogger</h1>
        <h2 className="textCenter">
          <style jsx global>
            {`
              .textCenter {
                background-color: green;
              }
            `}
          </style>
          Todays Highlits
        </h2>

        <Blog />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
